# Generated by Django 2.1.2 on 2018-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_retrieval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='first',
        ),
        migrations.AddField(
            model_name='topic',
            name='first_tweet',
            field=models.IntegerField(default=0),
        ),
    ]
