# Generated by Django 2.1.2 on 2018-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_retrieval', '0002_auto_20181226_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(default=0),
        ),
    ]
