# Generated by Django 2.1.2 on 2018-12-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_retrieval', '0003_topic_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
